version: "3.8"
services:
  mysql:
    container_name: local-mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mydb-data:/var/lib/mysql
volumes:
  mydb-data:
